#general 'mira' config, you can make config files for any floor in /config/FLOOR_NAME.yml

## Site settings
title: میرا
description: تست استفاده از میرا

author: kiavash
about: >
  میرا یک چارچوب یکپارچه مدیریت محتوا جهت ساختن وب‌سایتهای مجزا و چنگانه است
  با استفاده از میرا میتوانید همزمان و در کنار هم وبلاگ، فوتوبلاگ، گالری عکس، پادکست، کتاب، رزومه، معرفی‌کارها، صفحات پروژه، صفحات راهنما و ... را در طبقات ساختمان میرا مدیریت کنید. هر طبقه یک وب‌سایت مستقل است که با سایر طبقات در تعامل می‌باشد و می‌تواند تنظیم، قالب و اجزای خود را داشته باشد یا از خصوصیات طبقه‌ی مرکزی پیروی کند.
  
  برای استفاده از میرا نیاز به نصب هیچ برنامه‌ی اضافه مانند دیتابیس‌ها ندارید. تنها و تنها محتوایی که مینویسید و یک قالب برای ساختن خروجی وب‌سایت. میرا تمام کارهای باقی‌مانده را برای شما انجام خواهد داد
email: your-email@domain.com

url: http://localhost:80
root: /
static: /static
imageurl: /static/images

cover: /static/img/head-2.jpg
icon: /static/img/mira.png
logo: /static/img/mira.png

## default post permanent link
permalink: :year/:month/:day/:title/

## Build settings
default_markup: markmod

post_num: 3
archive_post_num: 10

default_floor: blog

template: maira

#this fields are not allowed: archives, static
lists:

socials:
 -  name: twitter
    icon: twitter
    url: https://twitter.com/Twitter_UserName
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

 -  name: github
    icon: github
    url: https://github.com/GitHub_UserName
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

 -  name: instagram
    icon: instagram
    url: https://instagram.com/NAME
    desc: Follow me
    share_url:
    share_title:
    share_link:

 -  name: google+
    icon: google-plus-square
    url: https://instagram.com/NAME
    desc: Follow me
    share_url:
    share_title:
    share_link:

 -  name: facebook
    icon: facebook-square
    url: https://instagram.com/NAME
    desc: Follow me
    share_url:
    share_title:
    share_link:
